baseURL = "https://gldanoob.dev/writeup/"
languageCode = 'en-us'
title = 'CTF Writeups'
pluralizelisttitles = false


[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^pandoc$"]

[markup]
defaultMarkdownHandler = "pandoc"
